name: CI Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests --batch-mode

      - name: Upload Build JAR
        uses: actions/upload-artifact@v6
        with:
          name: ip2region-JAR
          path: target/*.jar
